const { ACTIVE_THEME } = require('./src/theme/theme-config.shared');
const { themes } = require('./src/theme/themes/data');

const activeTheme = themes[ACTIVE_THEME];

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        indigo: {
          50: activeTheme.light.accentSoft,
          100: activeTheme.light.heroTextSoft,
          300: activeTheme.dark.aiGlow,
          400: activeTheme.dark.accent,
          500: activeTheme.light.accent,
          600: activeTheme.light.accentStrong,
          700: activeTheme.light.heroDropdownBg,
          800: activeTheme.dark.heroDropdownBg,
          900: activeTheme.dark.accentSoft,
        },
        slate: {
          50: activeTheme.light.page,
          100: activeTheme.light.surfaceAlt,
          200: activeTheme.light.border,
          300: activeTheme.light.borderStrong,
          400: activeTheme.light.textMuted,
          500: activeTheme.dark.textDisabled,
          600: activeTheme.light.textSoft,
          700: activeTheme.dark.borderStrong,
          800: activeTheme.dark.surface,
          900: activeTheme.dark.page,
        },
        emerald: {
          50: activeTheme.light.successBg,
          100: activeTheme.light.successBg,
          200: activeTheme.light.successBg,
          300: activeTheme.dark.successText,
          400: activeTheme.dark.success,
          500: activeTheme.light.success,
          600: activeTheme.light.successText,
          700: activeTheme.dark.successBg,
          900: activeTheme.dark.successBg,
          950: activeTheme.dark.successBg,
        },
        amber: {
          50: activeTheme.light.warningBg,
          100: activeTheme.light.warningBg,
          200: activeTheme.light.warningBg,
          300: activeTheme.dark.warningText,
          400: activeTheme.dark.warning,
          500: activeTheme.light.warning,
          600: activeTheme.light.warningText,
          700: activeTheme.dark.warningBg,
          800: activeTheme.dark.warningBg,
          900: activeTheme.dark.warningBg,
          950: activeTheme.dark.warningBg,
        },
        red: {
          50: activeTheme.light.dangerBg,
          300: activeTheme.dark.dangerText,
          400: activeTheme.dark.danger,
          500: activeTheme.light.danger,
          600: activeTheme.light.dangerText,
          900: activeTheme.dark.dangerBg,
          950: activeTheme.dark.dangerBg,
        },
        rose: {
          50: activeTheme.light.dangerBg,
          400: activeTheme.dark.danger,
          500: activeTheme.light.danger,
          600: activeTheme.light.dangerText,
          700: activeTheme.dark.dangerBg,
          900: activeTheme.dark.dangerBg,
        },
        orange: {
          500: activeTheme.light.warning,
          600: activeTheme.light.warningText,
        },
        'app-bg': 'var(--app-bg)',
        'app-bg-dark': 'var(--app-bg-dark)',
        'app-surface': 'var(--app-surface)',
        'app-surface-dark': 'var(--app-surface-dark)',
        'app-surface-alt': 'var(--app-surface-alt)',
        'app-surface-alt-dark': 'var(--app-surface-alt-dark)',
        'app-text': 'var(--app-text)',
        'app-text-dark': 'var(--app-text-dark)',
        'app-text-muted': 'var(--app-text-muted)',
        'app-text-muted-dark': 'var(--app-text-muted-dark)',
        'app-border': 'var(--app-border)',
        'app-border-dark': 'var(--app-border-dark)',
        'app-accent': 'var(--app-accent)',
        'app-accent-dark': 'var(--app-accent-dark)',
        'app-brand': 'var(--app-brand)',
        'app-success': 'var(--app-success)',
        'app-warning': 'var(--app-warning)',
        'app-danger': 'var(--app-danger)',
      },
      fontFamily: {
        'space-light':     ['SpaceGrotesk_300Light'],
        'space':           ['SpaceGrotesk_400Regular'],
        'space-medium':    ['SpaceGrotesk_500Medium'],
        'space-semibold':  ['SpaceGrotesk_600SemiBold'],
        'space-bold':      ['SpaceGrotesk_700Bold'],
        'space-extrabold': ['SpaceGrotesk_700Bold'],
      },
    },
  },
  plugins: [],
};
